"""Universal research agent — builds full project context for interactive Claude session."""

import logging
import re
from datetime import date
from pathlib import Path
from typing import Optional

from jinja2.sandbox import SandboxedEnvironment

from ..config import KlemmaConfig, ProjectConfig, resolve_prompt
from ..state import StateManager
from ..vault import VaultAdapter
from .planner import _get_current_deadline
from .work_context import _get_labels

logger = logging.getLogger(__name__)

# Context separator used by load_project_context() to join parent + child
_CONTEXT_SEPARATOR = "\n\n---\n\n"

# File extensions to list from project_root
_AGENT_SCAN_EXTENSIONS = {".md", ".tex", ".bib", ".txt", ".rst", ".pdf", ".doc", ".docx"}
_AGENT_SCAN_EXCLUDE = {".klemma", ".git", "__pycache__", ".venv", "node_modules", ".claude"}


def _scan_project_reports(project_root: Path) -> dict:
    """Scan project_root for reports and project files.

    Returns dict with:
    - outline_content: full text of Outline_*.md (truncated to 8000 chars)
    - report_index: list of {name, size} for Research_/Library_ reports
    - project_files: list of {name, size} for other project files
    """
    outline_content = ""
    report_index = []
    project_files = []

    for p in sorted(project_root.glob("*.md")):
        if p.name.startswith("Outline_"):
            try:
                outline_content = p.read_text(encoding="utf-8")[:8000]
            except OSError:
                pass
        elif p.name.startswith(("Research_", "Library_", "Agent_")):
            report_index.append({"name": p.name, "size": p.stat().st_size})
        elif not p.name.startswith("."):
            project_files.append({"name": p.name, "size": p.stat().st_size})

    # Scan notes/ subdirectories for reports (new layout)
    for subdir in ("research", "library", "agents"):
        notes_dir = project_root / "notes" / subdir
        if not notes_dir.is_dir():
            continue
        for p in sorted(notes_dir.glob("*.md")):
            rel = str(p.relative_to(project_root))
            report_index.append({"name": rel, "size": p.stat().st_size})

    # Also list non-.md files recursively (tex, bib, pdf, etc.)
    for p in sorted(project_root.rglob("*")):
        if not p.is_file() or p.suffix not in _AGENT_SCAN_EXTENSIONS:
            continue
        if p.suffix == ".md":
            continue  # already handled above
        rel_parts = p.relative_to(project_root).parts
        if any(part in _AGENT_SCAN_EXCLUDE for part in rel_parts):
            continue
        project_files.append({
            "name": str(p.relative_to(project_root)),
            "size": p.stat().st_size,
        })

    return {
        "outline_content": outline_content,
        "report_index": report_index,
        "project_files": project_files,
    }


def update_agents_index(project_root: Path) -> Optional[Path]:
    """Regenerate notes/AGENTS.md index from all agent report files.

    Scans notes/agents/ for Agent_*.md files, parses YAML frontmatter
    for date and query, and writes a sorted table to notes/AGENTS.md.

    Returns path to AGENTS.md if any agent files found, None otherwise.
    """
    agents_dir = project_root / "notes" / "agents"
    if not agents_dir.is_dir():
        return None

    agent_files = sorted(agents_dir.glob("Agent_*.md"), reverse=True)
    if not agent_files:
        return None

    rows = []
    for f in agent_files:
        file_date = ""
        query = ""
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
            # Parse YAML frontmatter
            fm_match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
            if fm_match:
                fm = fm_match.group(1)
                for line in fm.splitlines():
                    if line.startswith("date:"):
                        file_date = line.split(":", 1)[1].strip()
                    elif line.startswith("query:"):
                        query = line.split(":", 1)[1].strip().strip('"\'')
        except OSError:
            pass
        if not file_date:
            # Fallback: extract date from filename pattern Agent_*_YYYY-MM-DD_*
            date_match = re.search(r"(\d{4}-\d{2}-\d{2})", f.name)
            if date_match:
                file_date = date_match.group(1)
        rows.append({
            "file": f.name,
            "date": file_date,
            "query": query[:80],
        })

    lines = [
        "# Agent Reports Index",
        "",
        "*Auto-generated by klemma. Do not edit manually.*",
        "",
        "| Date | File | Query |",
        "|------|------|-------|",
    ]
    for r in rows:
        lines.append(f"| {r['date']} | [{r['file']}](agents/{r['file']}) | {r['query']} |")
    lines.append("")

    index_path = project_root / "notes" / "AGENTS.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Updated agents index: %s (%d entries)", index_path, len(rows))
    return index_path


def build_agent_context(
    config: KlemmaConfig,
    state: StateManager,
    vault: VaultAdapter,
    section: Optional[str] = None,
    chapter: Optional[int] = None,
    project: Optional[ProjectConfig] = None,
    dissertation_context: str = "",
    klemma_home: Optional[Path] = None,
    project_name: str = "",
    project_root: Optional[Path] = None,
    embeddings=None,
    query: Optional[str] = None,
    paper_store=None,
    user_library=None,
) -> str:
    """Build a rich system prompt with full research context for the agent.

    Gathers project structure, sources, coverage, gaps, fragments,
    today's plan, and reading queue. Renders via Jinja2 template.
    """
    # Deadline
    current_deadline, days_until_deadline = _get_current_deadline(config, project=project)

    # Chapter name
    if project:
        focus_chapter = chapter or project.current_chapter
        chapter_name = project.chapters.get(focus_chapter, f"Chapter {focus_chapter}")
        focus_section = section or project.current_section
        chapters = project.chapters
        scientific_results = project.scientific_results
        priority_terms = project.priority_terms
        min_sources = project.min_sources_per_section
    else:
        focus_chapter = chapter or config.dissertation.current_chapter
        chapter_name = config.dissertation.chapters.get(focus_chapter, f"Chapter {focus_chapter}")
        focus_section = section or config.dissertation.current_section
        chapters = config.dissertation.chapters
        scientific_results = config.dissertation.scientific_results
        priority_terms = config.dissertation.priority_terms
        min_sources = config.dissertation.min_sources_per_section

    # Sources: section-specific, chapter-specific, or all
    if section:
        sources = state.get_by_section(section)
        # Supplement with chapter sources
        if chapter:
            ch_sources = state.get_by_chapter(chapter)
        else:
            from ..config import parse_chapter_from_section

            ch = parse_chapter_from_section(section)
            ch_sources = state.get_by_chapter(ch) if ch else []
        seen = {s["id"] for s in sources}
        for cs in ch_sources:
            if cs["id"] not in seen:
                sources.append(cs)
                seen.add(cs["id"])
    elif chapter:
        sources = state.get_by_chapter(chapter)
    else:
        sources = state.get_all_sources()

    # Coverage & gaps
    coverage = state.get_coverage_stats()
    gaps = state.get_gaps(min_sources=min_sources)

    # Fragment stats
    fragment_stats = state.get_fragment_stats()

    # Today's plan
    today_plan = state.get_plan()

    # Reading queue
    next_reading = state.get_next_reading()

    # Split context: parent vs current project
    project_type = project.type if project else "dissertation"
    parts = dissertation_context.split(_CONTEXT_SEPARATOR)
    if len(parts) > 1:
        parent_context = _CONTEXT_SEPARATOR.join(parts[:-1])
        project_context = parts[-1]
    else:
        parent_context = ""
        project_context = dissertation_context

    # Adaptive labels based on project type and language
    labels = _get_labels(config.ai.language)
    ch_labels = labels["chapters"]
    chapters_label = ch_labels.get(project_type, ch_labels["_default"])
    # Singular form for coverage/fragment stats
    singular_map = {
        "Главы": "Глава", "Разделы": "Раздел",
        "Chapters": "Chapter", "Sections": "Section",
    }
    chapters_label_singular = singular_map.get(chapters_label, chapters_label)

    # Scan project_root for reports and project files
    outline_content = ""
    report_index = []
    project_file_list = []
    if project_root and project_root.is_dir():
        scan = _scan_project_reports(project_root)
        outline_content = scan["outline_content"]
        report_index = scan["report_index"]
        project_file_list = scan["project_files"]

    # Fragment RAG: retrieve relevant fragments when embeddings + query available
    relevant_fragments = []
    if embeddings and query:
        try:
            query_vec = embeddings.embed(query)
            if query_vec:
                relevant_fragments = state.retrieve_similar_fragments(
                    query_vec, top_k=10, model=embeddings.model_name
                )
        except Exception:
            logger.debug("Fragment RAG retrieval failed", exc_info=True)

    # Library supplement: pull relevant fragments from library.db when local state is empty
    if paper_store and user_library and len(relevant_fragments) < 5:
        from .context_loader import supplement_fragments_from_library

        _seen = {f.get("id", f.get("fragment_id", "")) for f in relevant_fragments}
        _lib_sources = sources[:20]  # limit to avoid large DB scans
        _added = supplement_fragments_from_library(
            relevant_fragments,
            _seen,
            _lib_sources,
            paper_store,
            user_library,
            section or "",
        )
        if _added:
            logger.debug(
                "Library supplement: added %d fragments from library.db", _added
            )

    # Render prompt
    prompt_path = (
        resolve_prompt("agent.md", klemma_home)
        if klemma_home
        else Path(__file__).parent.parent.parent.parent / "prompts" / "agent.md"
    )
    raw = prompt_path.read_text(encoding="utf-8")
    context = SandboxedEnvironment().from_string(raw).render(
        parent_context=parent_context,
        project_context=project_context,
        chapters=chapters,
        chapters_label=chapters_label,
        chapters_label_singular=chapters_label_singular,
        scientific_results=scientific_results,
        priority_terms=priority_terms,
        current_chapter=focus_chapter,
        chapter_name=chapter_name,
        current_section=focus_section,
        current_deadline=current_deadline,
        days_until_deadline=days_until_deadline,
        sources=sources,
        coverage=coverage,
        gaps=gaps,
        min_sources=min_sources,
        fragment_stats=fragment_stats,
        today_plan=today_plan,
        next_reading=next_reading,
        vault_path=config.obsidian.vault_path,
        today=date.today().isoformat(),
        language=config.ai.language,
        project_type=project_type,
        project_name=project_name,
        project_root=str(project_root) if project_root else "",
        outline_content=outline_content,
        report_index=report_index,
        project_file_list=project_file_list,
        relevant_fragments=relevant_fragments,
        range=range,
    )

    return context
