"""Project outline generation from directory contents + database context."""

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..ai import AIProvider
from ..config import (
    KlemmaConfig,
    ProjectConfig,
    parse_klemma_md,
    resolve_prompt,
    save_klemma_md,
    scan_project_files,
)
from ..state import StateManager
from .planner import _get_dissertation_context

logger = logging.getLogger(__name__)


@dataclass
class OutlineResult:
    """Structured outline generated by AI."""

    title: str = ""
    description: str = ""
    chapters: dict[int, str] = field(default_factory=dict)
    sections: dict[str, str] = field(default_factory=dict)
    scientific_results: dict[str, str] = field(default_factory=dict)
    outline_text: str = ""
    update_summary: str = ""


def _extract_outline_context(text: str) -> dict:
    """Extract user_notes, history, and previous_date from outline text."""
    # Extract '## ✏️ Что нового' / '## Notes' section
    user_notes = ""
    for marker in ("## ✏️ Что нового", "## Notes"):
        wn_idx = text.find(marker)
        if wn_idx != -1:
            after_wn = wn_idx + len(marker)
            next_heading = text.find("\n## ", after_wn)
            raw = text[after_wn:next_heading].strip() if next_heading != -1 else text[after_wn:].strip()
            if raw and not raw.startswith("_Запишите замечания"):
                user_notes = raw
            break

    # Extract '## 📋 История изменений' / '## History' section
    history = ""
    for marker in ("## 📋 История изменений", "## History"):
        hist_idx = text.find(marker)
        if hist_idx != -1:
            after_hist = hist_idx + len(marker)
            next_heading = text.find("\n## ", after_hist)
            history = text[after_hist:next_heading].strip() if next_heading != -1 else text[after_hist:].strip()
            break

    # Extract previous generation date
    date_match = re.search(r"\*Generated:\s*(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2})\*", text)
    previous_date = date_match.group(1) if date_match else ""

    return {
        "previous_text": text,
        "user_notes": user_notes,
        "history": history,
        "previous_date": previous_date,
    }


def _load_previous_outline(
    project_name: str,
    project_root: Path,
) -> Optional[dict]:
    """Read previous outline from KLEMMA.md ## Outline section, or Outline_*.md (fallback).

    Returns dict with keys:
    - previous_text: full outline text
    - user_notes: text from '## Notes' / '## ✏️ Что нового'
    - history: text from '## History' / '## 📋 История изменений'
    - previous_date: date string from *Generated: ...* line
    Returns None if no previous outline exists.
    """
    # 1. Try KLEMMA.md ## Outline section (new format)
    klemma_md_path = project_root / "KLEMMA.md"
    if klemma_md_path.exists():
        _, body = parse_klemma_md(klemma_md_path)
        outline_marker = "## Outline"
        ol_idx = body.find(outline_marker)
        if ol_idx != -1:
            # Extract outline section text
            after_ol = ol_idx + len(outline_marker)
            next_h2 = body.find("\n## ", after_ol)
            outline_text = body[after_ol:next_h2].strip() if next_h2 != -1 else body[after_ol:].strip()
            if outline_text:
                return _extract_outline_context(body[ol_idx:])

    # 2. Fallback: Outline_*.md (legacy format)
    outline_path = project_root / f"Outline_{project_name}.md"
    if not outline_path.exists():
        return None

    try:
        text = outline_path.read_text(encoding="utf-8")
    except OSError:
        return None

    if not text.strip():
        return None

    return _extract_outline_context(text)


def _build_new_history(
    user_notes: str,
    custom_prompt: str,
    existing_history: str,
    label: str = "",
) -> str:
    """Build updated history string from user notes, custom prompt, and existing history."""
    entries = []
    if label:
        entries.append(label)
    if user_notes:
        entries.append(user_notes)
    if custom_prompt:
        entries.append(f"**Directive:** {custom_prompt}")

    if not entries:
        return existing_history

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    archived_entry = f"### {timestamp}\n\n" + "\n\n".join(entries)

    if existing_history:
        return f"{archived_entry}\n\n{existing_history}"
    return archived_entry


def generate_outline(
    config: KlemmaConfig,
    state: StateManager,
    ai: AIProvider,
    project_root: Path,
    project_name: str = "",
    project: Optional[ProjectConfig] = None,
    dissertation_context: str = "",
    klemma_home: Optional[Path] = None,
    custom_prompt: str = "",
    force_initial: bool = False,
) -> tuple[OutlineResult, str]:
    """Generate project outline from directory files + database context.

    Returns (OutlineResult, mode) where mode is "initial" or "incremental".
    """
    # 1. Scan project files
    project_files = scan_project_files(project_root)

    # 2. Library context from DB
    library_summary = state.get_library_summary()

    # 3. Dissertation/project context
    context = dissertation_context or _get_dissertation_context(config, project)

    # 4. Check for previous outline (incremental mode)
    previous = None
    if project_name and not force_initial:
        previous = _load_previous_outline(project_name, project_root)

    mode = "incremental" if previous else "initial"

    # 5. Render prompt
    project_type = project.type if project else "dissertation"

    if mode == "incremental":
        prompt_name = "outline_incremental.md"
        prompt_path = resolve_prompt(prompt_name, klemma_home) if klemma_home else (
            Path(__file__).parent.parent.parent.parent / "prompts" / prompt_name
        )
        user_prompt = ai.render_prompt(
            prompt_path,
            project_type=project_type,
            dissertation_context=context,
            project_files=project_files,
            library_summary=library_summary,
            previous_outline=previous["previous_text"],
            user_notes=previous["user_notes"],
            previous_date=previous["previous_date"],
            custom_prompt=custom_prompt,
            language=config.ai.language,
        )
    else:
        prompt_name = "outline.md"
        prompt_path = resolve_prompt(prompt_name, klemma_home) if klemma_home else (
            Path(__file__).parent.parent.parent.parent / "prompts" / prompt_name
        )
        user_prompt = ai.render_prompt(
            prompt_path,
            project_type=project_type,
            dissertation_context=context,
            project_files=project_files,
            library_summary=library_summary,
            custom_prompt=custom_prompt,
            language=config.ai.language,
        )

    system = (
        f"You are an academic writing advisor for a {project_type}. "
        "Analyze project materials and generate a structured outline. "
        "Output only valid JSON."
    )

    # 6. AI call
    from klemma.ai import resolve_task_model

    task_name = "outline_incremental" if mode == "incremental" else "outline_initial"
    data = ai.call_json(
        system, user_prompt, max_tokens=4096,
        model_override=resolve_task_model(task_name, config.ai),
    )

    if not data:
        logger.error("Failed to generate outline")
        return OutlineResult(), mode

    # 7. Parse chapters with int keys
    raw_chapters = data.get("chapters", {})
    chapters = {}
    for k, v in raw_chapters.items():
        try:
            chapters[int(k)] = v
        except (ValueError, TypeError):
            chapters[k] = v

    result = OutlineResult(
        title=data.get("title", ""),
        description=data.get("description", ""),
        chapters=chapters,
        sections=data.get("sections", {}),
        scientific_results=data.get("scientific_results", {}),
        outline_text=data.get("outline_text", ""),
        update_summary=data.get("update_summary", ""),
    )

    # 8. Compute history for the saved file
    history = ""
    if previous:
        history = _build_new_history(
            previous["user_notes"], custom_prompt, previous["history"],
        )
    elif force_initial and project_name:
        # --fresh: archive previous outline reference in history
        old = _load_previous_outline(project_name, project_root)
        if old:
            history = _build_new_history(
                old["user_notes"], custom_prompt, old["history"],
                label="🔄 Full regeneration",
            )

    result._history = history  # noqa: SLF001

    return result, mode


def save_outline(
    result: OutlineResult,
    project_name: str,
    project_root: Path,
) -> Path:
    """Save outline to KLEMMA.md (frontmatter + ## Outline section in body).

    Updates frontmatter with chapters/sections/scientific_results from result.
    Replaces ## Outline section in body with new outline text.
    Preserves ## Notes and ## History sections.

    Falls back to writing Outline_*.md if KLEMMA.md does not exist.
    Returns path of the file written.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    history = getattr(result, "_history", "")

    klemma_md_path = project_root / "KLEMMA.md"

    # --- Build outline text block ---
    outline_lines = [
        f"*Generated: {timestamp}*",
        "",
    ]
    if result.description:
        outline_lines.append(f"**Description:** {result.description}")
        outline_lines.append("")
    if result.update_summary:
        outline_lines.append(f"> **Обновление:** {result.update_summary}")
        outline_lines.append("")
    if result.scientific_results:
        outline_lines.append("### Scientific Contributions")
        for key, value in result.scientific_results.items():
            outline_lines.append(f"- **{key}:** {value}")
        outline_lines.append("")
    if result.outline_text:
        outline_lines.append("### Detailed Outline")
        outline_lines.append("")
        outline_lines.append(result.outline_text)
        outline_lines.append("")
    new_outline_text = "\n".join(outline_lines)

    # --- Write to KLEMMA.md ---
    if klemma_md_path.exists():
        fm, body = parse_klemma_md(klemma_md_path)

        # Update frontmatter with outline data
        if result.title:
            fm["title"] = result.title
        if result.chapters:
            fm["chapters"] = result.chapters
        if result.sections:
            fm["sections"] = result.sections
        if result.scientific_results:
            fm["scientific_results"] = result.scientific_results

        # Replace ## Outline section in body (preserve ## Notes and ## History)
        notes_text = ""
        notes_match = re.search(r"^## Notes\s*\n(.*?)(?=^## |\Z)", body, re.MULTILINE | re.DOTALL)
        if notes_match:
            notes_text = notes_match.group(0)
        history_text = ""
        history_match = re.search(r"^## History\s*\n(.*?)(?=^## |\Z)", body, re.MULTILINE | re.DOTALL)
        if history_match:
            history_text = history_match.group(0)

        # Strip existing ## Outline / ## Notes / ## History from body
        body_clean = re.sub(r"^## (Outline|Notes|History)\s*\n.*?(?=^## |\Z)", "", body,
                            flags=re.MULTILINE | re.DOTALL).rstrip()

        # Build new body with updated outline
        new_body_parts = [body_clean, "", "## Outline", "", new_outline_text]

        if notes_text:
            new_body_parts.extend(["", notes_text.rstrip()])
        else:
            new_body_parts.extend([
                "",
                "## Notes",
                "",
                "_Запишите замечания, идеи по структуре —",
                "всё, что учесть при следующем запуске `klemma outline`._",
                "",
            ])

        if history_text:
            new_body_parts.extend(["", history_text.rstrip()])
        else:
            new_body_parts.extend(["", "## History", ""])
            if history:
                new_body_parts.append(history)

        new_body = "\n".join(new_body_parts) + "\n"
        save_klemma_md(klemma_md_path, fm, new_body)
        return klemma_md_path

    # --- Fallback: write Outline_*.md (legacy / no KLEMMA.md) ---
    content_lines = [
        f"# Outline: {result.title}",
        f"*Generated: {timestamp}*",
        "",
    ]
    if result.description:
        content_lines.append(f"**Description:** {result.description}")
        content_lines.append("")
    if result.update_summary:
        content_lines.append(f"> **Обновление:** {result.update_summary}")
        content_lines.append("")
    if result.scientific_results:
        content_lines.append("## Scientific Contributions")
        for key, value in result.scientific_results.items():
            content_lines.append(f"- **{key}:** {value}")
        content_lines.append("")
    if result.outline_text:
        content_lines.append("## Detailed Outline")
        content_lines.append("")
        content_lines.append(result.outline_text)
        content_lines.append("")
    content_lines.extend([
        "---", "",
        "## ✏️ Что нового", "",
        "_Запишите замечания, идеи по структуре, новые разделы —",
        "всё, что учесть при следующем запуске `klemma outline`._", "",
        "## 📋 История изменений", "",
    ])
    if history:
        content_lines.append(history)
        content_lines.append("")

    content = "\n".join(content_lines)
    path = project_root / f"Outline_{project_name}.md"
    path.write_text(content, encoding="utf-8")
    return path
