"""Project outline generation from directory contents + database context."""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from ..ai import AIProvider
from ..config import KlemmaConfig, ProjectConfig, resolve_prompt, scan_project_files
from ..state import StateManager
from ..vault import VaultAdapter
from .planner import _get_dissertation_context

logger = logging.getLogger(__name__)


@dataclass
class OutlineResult:
    """Structured outline generated by AI."""

    title: str = ""
    description: str = ""
    chapters: dict[int, str] = field(default_factory=dict)
    sections: dict[str, str] = field(default_factory=dict)
    scientific_results: dict[str, str] = field(default_factory=dict)
    outline_text: str = ""


def generate_outline(
    config: KlemmaConfig,
    state: StateManager,
    ai: AIProvider,
    project_root: Path,
    project: Optional[ProjectConfig] = None,
    dissertation_context: str = "",
    klemma_home: Optional[Path] = None,
) -> OutlineResult:
    """Generate project outline from directory files + database context.

    Scans project directory for .md/.tex/.bib files, combines with
    library statistics from DB, and sends to AI for structured analysis.
    """
    # 1. Scan project files
    project_files = scan_project_files(project_root)

    # 2. Library context from DB
    library_summary = state.get_library_summary()

    # 3. Dissertation/project context
    context = dissertation_context or _get_dissertation_context(config, project)

    # 4. Render prompt
    project_type = project.type if project else "dissertation"
    prompt_path = resolve_prompt("outline.md", klemma_home) if klemma_home else (
        Path(__file__).parent.parent.parent.parent / "prompts" / "outline.md"
    )
    user_prompt = ai.render_prompt(
        prompt_path,
        project_type=project_type,
        dissertation_context=context,
        project_files=project_files,
        library_summary=library_summary,
        language=config.ai.language,
    )

    system = (
        f"You are an academic writing advisor for a {project_type}. "
        "Analyze project materials and generate a structured outline. "
        "Output only valid JSON."
    )

    # 5. AI call
    data = ai.call_json(system, user_prompt, max_tokens=4096)

    if not data:
        logger.error("Failed to generate outline")
        return OutlineResult()

    # 6. Parse chapters with int keys
    raw_chapters = data.get("chapters", {})
    chapters = {}
    for k, v in raw_chapters.items():
        try:
            chapters[int(k)] = v
        except (ValueError, TypeError):
            chapters[k] = v

    return OutlineResult(
        title=data.get("title", ""),
        description=data.get("description", ""),
        chapters=chapters,
        sections=data.get("sections", {}),
        scientific_results=data.get("scientific_results", {}),
        outline_text=data.get("outline_text", ""),
    )


def format_klemma_md(result: OutlineResult, project_type: str = "paper") -> str:
    """Format OutlineResult into enriched KLEMMA.md content."""
    lines = [
        "# Project Context",
        "",
        f'Topic: "{result.title}"',
        "",
        f"Description: {result.description}",
        "",
    ]

    # Structure
    if result.chapters or result.sections:
        lines.append("## Structure")
        lines.append("")
        for ch_num in sorted(result.chapters.keys()):
            ch_title = result.chapters[ch_num]
            lines.append(f"### {ch_num}. {ch_title}")
            # Add sections for this chapter
            ch_prefix = f"{ch_num}."
            ch_sections = {
                k: v for k, v in result.sections.items()
                if k.startswith(ch_prefix)
            }
            for sec_id in sorted(ch_sections.keys()):
                lines.append(f"- {sec_id} {ch_sections[sec_id]}")
            lines.append("")

    # Scientific results
    if result.scientific_results:
        lines.append("Scientific Results:")
        for key, value in result.scientific_results.items():
            lines.append(f"- {key}: {value}")
        lines.append("")

    return "\n".join(lines)


def save_outline_to_vault(
    result: OutlineResult,
    project_name: str,
    vault: VaultAdapter,
    config: KlemmaConfig,
) -> Path:
    """Save full outline as a vault note."""
    note_name = f"Outline_{project_name}"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    content_lines = [
        f"# Outline: {result.title}",
        f"*Generated: {timestamp}*",
        "",
    ]

    if result.description:
        content_lines.append(f"**Description:** {result.description}")
        content_lines.append("")

    if result.scientific_results:
        content_lines.append("## Scientific Contributions")
        for key, value in result.scientific_results.items():
            content_lines.append(f"- **{key}:** {value}")
        content_lines.append("")

    if result.outline_text:
        content_lines.append("## Detailed Outline")
        content_lines.append("")
        content_lines.append(result.outline_text)

    content = "\n".join(content_lines)
    folder = config.obsidian.notes_folder
    return vault.create_note(note_name, content, folder=folder)
